name        : libxfixes
version     : 5.0.1
release     : 7
source      :
    - http://xorg.freedesktop.org/releases/individual/lib/libXfixes-5.0.1.tar.bz2 : 63bec085084fa3caaee5180490dd871f1eb2020ba9e9b39a30f93693ffc34767
license     :
    - MIT
summary     : X11 miscellaneous 'fixes' extension library
component   : xorg.library
builddeps   :
    - pkgconfig(fixesproto)
    - pkgconfig(xextproto)
    - pkgconfig(x11)
    - pkgconfig32(x11)
    - glibc-32bit-devel
    - libgcc-32bit
emul32      : yes
optimize    : speed
patterns    :
    - devel:
        - /usr/share/man
description : |
    libXfixes provides an X Window System client interface to the 'XFIXES' extension to the X protocol.
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
