name       : libxfixes
version    : 5.0.3
release    : 8
source     :
    - https://www.x.org/releases/individual/lib/libXfixes-5.0.3.tar.gz : 9ab6c13590658501ce4bd965a8a5d32ba4d8b3bb39a5a5bc9901edffc5666570
license    :
    - MIT
summary    : X11 miscellaneous 'fixes' extension library
component  : xorg.library
builddeps  :
    - pkgconfig(fixesproto)
    - pkgconfig(xextproto)
    - pkgconfig(x11)
    - pkgconfig32(x11)
    - glibc-32bit-devel
    - libgcc-32bit
emul32     : yes
optimize   : speed
patterns   :
    - devel :
        - /usr/share/man
description: |
    libXfixes provides an X Window System client interface to the 'XFIXES' extension to the X protocol.
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
